---
# Source: myapp-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: myapp1
  namespace: team31
spec:
  selector:
    app: myapp1
  type: ClusterIP
  ports:
  - name: myapp1
    protocol: TCP
    port: 8080
    targetPort: 8080
---
# Source: myapp-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1
  namespace: team31
spec:
  selector:
    matchLabels:
      app: myapp1
  template:
    metadata:
      labels:
        app: myapp1
    spec:
      containers:
      - name: myapp1
        image: team31
        imagePullPolicy: Never
        resources:
          limits:
            memory: "50Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 3
          failureThreshold: 3
          successThreshold: 3
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
---
# Source: myapp-chart/templates/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: myapp1
  namespace: team31
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapp1
  minReplicas: 2
  maxReplicas: 7
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10

