@team31_HostAddress = http://localhost:5122

GET {{team31_HostAddress}}/hello/
Accept: application/json
###
GET {{team31_HostAddress}}/health/readiness
Accept: application/json
###
GET {{team31_HostAddress}}/health/liveness
Accept: application/json